version: "3"

services: 
  # web:
  #   build: .
  #   command: python run.py 
  #   ports: 
  #     - 8087:8000
  #   volumes:
  #     - .:/code

  mongo:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
    ports: 
      - 27017:27017
  
  mongo-express:
    image: mongo-express
    ports:
        - 8088:8081
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
        - mongo
    