version: "3"

services: 
  # web:
  #   build: .
  #   image: backend:v1
  #   command: python run.py 
  #   ports: 
  #     - 8087:8000
  #   volumes:
  #     - .:/code

  mongo:
    image: mongo:4.4.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped
    volumes:
      - ./data:/data/db
    ports: 
      - 27017:27017
  
  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8088:8081
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
    
networks:
  default:
    name: collab_circle