# Generated by Django 3.1.1 on 2020-10-05 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('No_collaborators_req', models.IntegerField(default=0)),
                ('Skills_collaborator', models.CharField(max_length=100)),
                ('Status_project', models.CharField(max_length=100)),
                ('No_applicants', models.IntegerField(default=1)),
                ('Estimated_completion', models.IntegerField(default=30)),
            ],
        ),
    ]
